# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    ThreeOrgsOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
                # - *OrdererUSOrg
        Consortiums:
            ExampleConsortium:
                Organizations:
                    - *Org1
                    - *Org2
                    - *Org3
            # NeospykarConsortium:
            #     Organizations:
            #         - *Org4
            #         - *Org5

    ThreeOrgsChannel:
        Consortium: ExampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2
                - *Org3

    # NeospykarOrgsChannel:
    #     Consortium: NeospykarConsortium
    #     Application:
    #         <<: *ApplicationDefaults
    #         Organizations:
    #             - *Org4
    #             - *Org5

    # NeospykarOrgsOrdererGenesis:
    #     Orderer:
    #         <<: *OrdererDefaults
    #         Organizations:
    #             - *OrdererUSOrg
    #     Consortiums:

    # NeospykarOrgsChannel:
    #     Consortium: NeospykarConsortium
    #     Application:
    #         <<: *ApplicationDefaults
    #         Organizations:
    #             - *Org4
    #             - *Org5

################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    # SampleOrg defines an MSP using the sampleconfig.  It should never be used
    # in production but may be used as a template for other definitions
    - &OrdererOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrdererOrg

        # ID to load the MSP definition as
        ID: OrdererMSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/neo.com/msp

    - &Org1
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Org1MSP

        # ID to load the MSP definition as
        ID: Org1MSP

        MSPDir: crypto-config/peerOrganizations/org1.neo.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.org1.neo.com
              Port: 7051

    - &Org2
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Org2MSP

        # ID to load the MSP definition as
        ID: Org2MSP

        MSPDir: crypto-config/peerOrganizations/org2.neo.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.org2.neo.com
              Port: 7051
    - &Org3
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Org3MSP

        # ID to load the MSP definition as
        ID: Org3MSP

        MSPDir: crypto-config/peerOrganizations/org3.neo.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.org3.neo.com
              Port: 7051

    # - &OrdererUSOrg
    #     # DefaultOrg defines the organization which is used in the sampleconfig
    #     # of the fabric.git development environment
    #     Name: OrdererUSOrg
    #
    #     # ID to load the MSP definition as
    #     ID: OrdererUSMSP
    #
    #     # MSPDir is the filesystem path which contains the MSP configuration
    #     MSPDir: crypto-config/ordererOrganizations/neospykar.com/msp
    #
    # - &Org4
    #     # DefaultOrg defines the organization which is used in the sampleconfig
    #     # of the fabric.git development environment
    #     Name: Org4MSP
    #
    #     # ID to load the MSP definition as
    #     ID: Org4MSP
    #
    #     MSPDir: crypto-config/peerOrganizations/org4.neospykar.com/msp
    #
    #     AnchorPeers:
    #         # AnchorPeers defines the location of peers which can be used
    #         # for cross org gossip communication.  Note, this value is only
    #         # encoded in the genesis block in the Application section context
    #         - Host: peer0.org4.neospykar.com
    #           Port: 7051
    #
    # - &Org5
    #     # DefaultOrg defines the organization which is used in the sampleconfig
    #     # of the fabric.git development environment
    #     Name: Org5MSP
    #
    #     # ID to load the MSP definition as
    #     ID: Org5MSP
    #
    #     MSPDir: crypto-config/peerOrganizations/org5.neospykar.com/msp
    #
    #     AnchorPeers:
    #         # AnchorPeers defines the location of peers which can be used
    #         # for cross org gossip communication.  Note, this value is only
    #         # encoded in the genesis block in the Application section context
    #         - Host: peer0.org5.neospykar.com
    #           Port: 7051

################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: solo

    Addresses:
        - orderer1.neo.com:7050
        # - orderer2.neo.com:7060
        # - orderer1.neospykar.com:8050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:
